apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.openshift.io/v1alpha1",
          "kind": "Kueue",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "kueue-operator"
            },
            "name": "cluster",
            "namespace": "openshift-kueue-operator"
          },
          "spec": {
            "config": {
              "integrations": {
                "frameworks": [
                  "BatchJob"
                ]
              }
            },
            "managementState": "Managed"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-30T20:04:54Z"
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    console.openshift.io/operator-monitoring-default: "true"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/cluster-monitoring: "true"
    operatorframework.io/suggested-namespace: openshift-kueue-operator
    operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift Container Platform", "OpenShift Platform Plus"]'
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
  name: kueue-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Kueue
      name: kueues.operator.openshift.io
      version: v1alpha1
  description: Kueue Operator description. TODO.
  displayName: Red Hat Build of Kueue
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - operator.openshift.io
          resources:
          - kueues
          - kueues/status
          - kueues/finalizers
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - watch
          - deletecollection
          - list
          - create
          - update
          - delete
          - patch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
          - bind
          - escalate
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          - serviceaccounts
          - events
          - pods
          - secrets
          - configmaps
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          - apiservers
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - watch
          - list
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - issuers
          - certificates
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: openshift-kueue-operator
      deployments:
      - name: openshift-kueue-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              name: openshift-kueue-operator
          strategy: {}
          template:
            metadata:
              labels:
                app.openshift.io/name: kueue
                name: openshift-kueue-operator
            spec:
              containers:
              - args:
                - operator
                command:
                - kueue-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: openshift-kueue-operator
                - name: RELATED_IMAGE_OPERAND_IMAGE
                  value: registry.redhat.io/kueue-tech-preview/kueue-rhel9@sha256:56e3aca8165f9aad48372ee2b746a9d75756f1e8c3613e94d7ea554afe878122
                image: registry.redhat.io/kueue-tech-preview/kueue-rhel9-operator@sha256:0c4d9cd97f7579adbf2afd238c953ca5f170408cf27e3b2bf4aa16c108a76881
                imagePullPolicy: Always
                name: openshift-kueue-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
                volumeMounts:
                - mountPath: /tmp
                  name: tmp
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: openshift-kueue-operator
              volumes:
              - emptyDir: {}
                name: tmp
      permissions:
      - rules:
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: openshift-kueue-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kueue-operator
  links:
  - name: Kueue Operator
    url: https://github.com/openshift/kueue-operator
  maintainers:
  - email: aos-node@redhat.com
    name: Node team
  maturity: alpha
  provider:
    name: Red Hat, Inc
    url: https://github.com/openshift/kueue-operator
  relatedImages:
  - image: registry.redhat.io/kueue-tech-preview/kueue-rhel9@sha256:56e3aca8165f9aad48372ee2b746a9d75756f1e8c3613e94d7ea554afe878122
    name: operand-image
  version: 0.1.0
  minKubeVersion: 1.28.0
