apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kueue-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kueue is the Schema for the Kueue API
      displayName: Kueue Operator
      kind: Kueue
      name: operator.openshift.io.kueue
      version: v1beta1
  description: Operator for installing kueue into openshift
  displayName: kueue-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kueue
  links:
  - name: Kueue Operator
    url: https://kueue-operator.domain
  maintainers:
  - email: kehannon@redhat.com
    name: kannon92
  maturity: alpha
  provider:
    name: openshift
  version: 0.0.0
