apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-kueue-operator
  namespace: openshift-kueue-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-kueue-operator
  template:
    metadata:
      labels:
        name: openshift-kueue-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: openshift-kueue-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/kevin-oss/kueue-operator:jan24-305
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - kueue-operator
          args:
            - "operator"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "openshift-kueue-operator"
            - name: RELATED_IMAGE_OPERAND_IMAGE
              value: registry.k8s.io/kueue/kueue:v0.10.0
      serviceAccountName: openshift-kueue-operator
      volumes:
        - name: tmp
          emptyDir: {}
