apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
    service.beta.openshift.io/serving-cert-secret-name: kueue-webhook-server-cert
  name: kueue-webhook-service
  namespace: openshift-kueue-operator
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager